name: Staging CI
on:
  push:
    branches: [staging]

jobs:
  start:
    runs-on: beta
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - run: npm ci
      - run: npm run build --if-present
      - run: node ./.github/pm2.js accounts start 3000
