name: Testing CI
on:
  push:
    branches: [testing]

jobs:
  start:
    runs-on: robert
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: true
      - run: |
          npm ci
          node ./.github/pm2.js accounts dev 3000
