name: Testing CI
on:
  push:
    branches: [testing]

jobs:
  start:
    runs-on: robert
    steps:
      - uses: actions/checkout@v2

      - run: |
          npm ci
          node ./.github/pm2.js products dev 3001
